export const US_STATES = [
  { fullName: 'Alabama', code: 'AL' },
  { fullName: 'Alaska', code: 'AK' },
  { fullName: 'Arizona', code: 'AZ' },
  { fullName: 'Arkansas', code: 'AR' },
  { fullName: 'California', code: 'CA' },
  { fullName: 'Colorado', code: 'CO' },
  { fullName: 'Connecticut', code: 'CT' },
  { fullName: 'Delaware', code: 'DE' },
  { fullName: 'District of Columbia', code: 'DC' },
  { fullName: 'Florida', code: 'FL' },
  { fullName: 'Georgia', code: 'GA' },
  { fullName: 'Hawaii', code: 'HI' },
  { fullName: 'Idaho', code: 'ID' },
  { fullName: 'Illinois', code: 'IL' },
  { fullName: 'Indiana', code: 'IN' },
  { fullName: 'Iowa', code: 'IA' },
  { fullName: 'Kansas', code: 'KS' },
  { fullName: 'Kentucky', code: 'KY' },
  { fullName: 'Louisiana', code: 'LA' },
  { fullName: 'Maine', code: 'ME' },
  { fullName: 'Maryland', code: 'MD' },
  { fullName: 'Massachusetts', code: 'MA' },
  { fullName: 'Michigan', code: 'MI' },
  { fullName: 'Minnesota', code: 'MN' },
  { fullName: 'Mississippi', code: 'MS' },
  { fullName: 'Missouri', code: 'MO' },
  { fullName: 'Montana', code: 'MT' },
  { fullName: 'Nebraska', code: 'NE' },
  { fullName: 'Nevada', code: 'NV' },
  { fullName: 'New Hampshire', code: 'NH' },
  { fullName: 'New Jersey', code: 'NJ' },
  { fullName: 'New Mexico', code: 'NM' },
  { fullName: 'New York', code: 'NY' },
  { fullName: 'North Carolina', code: 'NC' },
  { fullName: 'North Dakota', code: 'ND' },
  { fullName: 'Ohio', code: 'OH' },
  { fullName: 'Oklahoma', code: 'OK' },
  { fullName: 'Oregon', code: 'OR' },
  { fullName: 'Pennsylvania', code: 'PA' },
  { fullName: 'Rhode Island', code: 'RI' },
  { fullName: 'South Carolina', code: 'SC' },
  { fullName: 'South Dakota', code: 'SD' },
  { fullName: 'Tennessee', code: 'TN' },
  { fullName: 'Texas', code: 'TX' },
  { fullName: 'Utah', code: 'UT' },
  { fullName: 'Vermont', code: 'VT' },
  { fullName: 'Virginia', code: 'VA' },
  { fullName: 'Washington', code: 'WA' },
  { fullName: 'West Virginia', code: 'WV' },
  { fullName: 'Wisconsin', code: 'WI' },
  { fullName: 'Wyoming', code: 'WY' },
];
